// GENERATED by rtl/tb/make_mac_vectors.py -- do not edit.
`ifndef KWS_MAC_EXPECT_VH
`define KWS_MAC_EXPECT_VH
`define K13_EXPECT -5
`define K13_NWORDS 1
`define K29_EXPECT 3
`define K29_NWORDS 1
`define W31_EXPECT -1
`define W31_NWORDS 1
`define W32_EXPECT -2
`define W32_NWORDS 1
`define W33_EXPECT -3
`define W33_NWORDS 2
`define C64_EXPECT 4
`define C64_NWORDS 2
`define C128_EXPECT -4
`define C128_NWORDS 4
`endif
