"""1000-clip vectors -> a CLIPS-sized slice the self-test ROM can hold.

Why slicing is necessary rather than just reading less: `$readmemh`'s optional
arguments are MEMORY addresses, not file offsets. There is no way to say "skip
the first 600 clips of this file". So the offset has to be resolved on the file
side, and a ROM declared for 600 clips must be fed a 600-clip file -- pointing
it at the 1000-clip file relies on the simulator quietly stopping at the array
end, which is the kind of tolerance `rtl/README.md` 3-07 already paid for once.

Why a slice at all: 1000 clips x 128 frames x 32 bits is 4,096 Kbit and the
part has ~3,130 Kbit of BRAM left after the network. About 680 clips fit at the
declared 32-bit width (docs/fpga_primitives.md 4). Sweeping thousands means
several bitstreams with different --base, which is what this script is for.

    python -m export.slice_selftest rtl/gen/bd_base/selftest \
        --clips 600 --base 0 --out out/selftest/bd_base

Writes clips.hex, expected.hex and a paths.vh of `KWS_ST_*` macros, so the
directory drops straight into `rtl/run_xsim.ps1 -Vectors`.

Stdlib only -- runs under Vivado's bundled interpreter on a machine with no
project Python.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("vectors", help="rtl/gen/<tag>/selftest")
    ap.add_argument("--clips", type=int, default=600)
    ap.add_argument("--base", type=int, default=0, help="first clip to include")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    src = Path(args.vectors)
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    # T comes from the dump's own manifest, not from a literal here. A hardcoded
    # 128 would silently mis-slice the moment T changes, and the symptom would be
    # clips that look like each other's tails.
    man = json.loads((src / "golden.json").read_text())
    shape = man["files"]["input"]["shape"]          # [N, C, T]
    n_total, _, t_in = (int(v) for v in shape)

    exp_src = src / "expected.hex"
    if not exp_src.exists():
        raise SystemExit(
            f"{exp_src} not found -- run first:\n"
            f"    python -m export.predictions_to_hex {src}")

    lo, hi = args.base, args.base + args.clips
    if hi > n_total:
        raise SystemExit(
            f"asked for clips [{lo}, {hi}) but the dump holds {n_total}. "
            f"Lower --clips or --base.")

    clips_in = (src / "input.hex").read_text().split()
    if len(clips_in) != n_total * t_in:
        raise SystemExit(
            f"input.hex has {len(clips_in)} words, expected "
            f"{n_total * t_in} ({n_total} clips x {t_in} frames)")
    exp_in = exp_src.read_text().split()
    if len(exp_in) != n_total:
        raise SystemExit(
            f"expected.hex has {len(exp_in)} lines, expected {n_total}")

    (out / "clips.hex").write_text(
        "\n".join(clips_in[lo * t_in:hi * t_in]) + "\n")
    (out / "expected.hex").write_text("\n".join(exp_in[lo:hi]) + "\n")

    # A distinct prefix from KWS_GOLD_* so the two can coexist: the gold macros
    # describe the FULL dump, these describe the slice actually in the ROM.
    # Conflating them is how a 600-clip ROM ends up being told it has 1000.
    rel = out.as_posix()
    (out / "paths.vh").write_text("\n".join([
        "// GENERATED by export/slice_selftest.py -- do not edit.",
        f"// clips [{lo}, {hi}) of {n_total} from {src.as_posix()}",
        "`ifndef KWS_ST_VH",
        "`define KWS_ST_VH",
        f"`define KWS_ST_CLIPS     {args.clips}",
        f"`define KWS_ST_BASE      {lo}",
        f"`define KWS_ST_T_IN      {t_in}",
        f'`define KWS_ST_CLIP_FILE "{rel}/clips.hex"',
        f'`define KWS_ST_EXP_FILE  "{rel}/expected.hex"',
        "`endif",
        "",
    ]))

    print(f"clips [{lo}, {hi}) of {n_total} -> {out}")
    print(f"  clips.hex     {args.clips * t_in} words")
    print(f"  expected.hex  {args.clips} lines")
    print(f"  ROM cost      {args.clips * t_in * 32 / 1024:.0f} Kbit at 32-bit")


if __name__ == "__main__":
    main()
