"""Streaming chip vectors -> a CASES-sized slice for the ROM, plus paths.vh.

    python -m export.slice_stream_selftest rtl/gen/bd_base_ft20_partial75/stream_selftest \
        --cases 240 --base 0 --out out/stream_selftest/p75
    python -m export.slice_stream_selftest rtl/gen/bd_base_ft20_partial75/stream_selftest \
        --cases 1 --base 0 --out out/stream_selftest/p75_sim

Same reason as export/slice_selftest.py: $readmemh ranges are memory addresses,
so an offset is resolved on the file side. Frames and expected words are cut
from the same case range, and the trace rows for those cases are copied too so
a simulation log can be diffed window by window.

Stdlib only.
"""
from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("vectors")
    ap.add_argument("--cases", type=int, required=True)
    ap.add_argument("--base", type=int, default=0)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    src, out = Path(args.vectors), Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    man = json.loads((src / "stream_manifest.json").read_text())
    n, fpc, wpc = man["cases"], man["frames_per_case"], man["windows_per_case"]
    lo, hi = args.base, args.base + args.cases
    if hi > n:
        raise SystemExit(f"cases [{lo}, {hi}) but the export holds {n}")

    frames = (src / "stream_frames.hex").read_text().split()
    exp = (src / "stream_expected.hex").read_text().split()
    if len(frames) != n * fpc or len(exp) != n:
        raise SystemExit(f"file lengths {len(frames)}, {len(exp)} do not match {n} cases x {fpc} frames")
    (out / "stream_frames.hex").write_text("\n".join(frames[lo * fpc:hi * fpc]) + "\n")
    (out / "stream_expected.hex").write_text("\n".join(exp[lo:hi]) + "\n")

    with open(src / "stream_trace.csv", newline="") as fi, \
         open(out / "stream_trace.csv", "w", newline="") as fo:
        rd = csv.DictReader(fi)
        wr = csv.DictWriter(fo, fieldnames=rd.fieldnames)
        wr.writeheader()
        for row in rd:
            if lo <= int(row["rom_case"]) < hi:
                row["rom_case"] = str(int(row["rom_case"]) - lo)
                wr.writerow(row)

    rel = out.as_posix()
    (out / "paths.vh").write_text("\n".join([
        "// GENERATED by export/slice_stream_selftest.py -- do not edit.",
        f"// cases [{lo}, {hi}) of {n} from {src.as_posix()}",
        "`ifndef KWS_SST_VH", "`define KWS_SST_VH",
        f"`define KWS_SST_CASES      {args.cases}",
        f"`define KWS_SST_BASE       {lo}",
        f"`define KWS_SST_FRAMES     {fpc}",
        f"`define KWS_SST_WINDOWS    {wpc}",
        f'`define KWS_SST_FRAME_FILE "{rel}/stream_frames.hex"',
        f'`define KWS_SST_EXP_FILE   "{rel}/stream_expected.hex"',
        "`endif", "",
    ]))
    print(f"cases [{lo}, {hi}) of {n} -> {out}: {args.cases * fpc} frame words, "
          f"ROM {args.cases * fpc * 16 / 1000:.0f} kbit")


if __name__ == "__main__":
    main()
