# 배치 합성 — GUI 없이 한 줄로. 결과가 재현 가능해진다.
#
#   vivado -mode batch -source rtl/build.tcl
#   vivado -mode batch -source rtl/build.tcl -tclargs -part xc7s75fgga484-2
#   vivado -mode batch -source rtl/build.tcl -tclargs -tag fx_ste0003 -impl
#
# 리포 루트에서 돌린다. 산출물은 out/synth/<part>/ 에 쌓인다.
#
# 파트 기본값은 XC7S75 (Spartan-7, FGGA484) 다. KC705 를 쓸 수 없게 되어
# 2026-09-02 에 바뀌었다. 그 전에는 여기 "xc7k325t 는 무료 Vivado ML Standard
# 대상이 아니다(Enterprise 필요)" 라고 적혀 있었는데, **Spartan-7 은 무료 대상**
# 이므로 그 제약이 사라졌다 -- 합성부터 비트스트림까지 라이선스가 필요 없고,
# 연구실이 아니라 어디서든 돌릴 수 있다.
#
# 속도 등급 -1 은 **킷 매뉴얼로 확정**됐다 (2026-09-07). CH2 의 New Project 예제가
# `xc7s75fgga484-1` 을 못박는다 -- docs/hanback_kit.md 1. 한때 여기 "확인 전 값"
# 이라고 적혀 있었다. -1 은 이 패키지의 가장 느린 상용 등급이라 우리에게 유리하다:
# 느린 등급에서 타이밍이 통과하면 빠른 등급에서도 통과한다.
#
# 설치 직후 한 번은 `rtl/probe_part.tcl` 을 돌린다 -- 파트 존재, Exp. Port 볼의
# 뱅크, 클럭 핀의 MRCC 여부를 한꺼번에 답한다.

set ROOT [file normalize [file join [file dirname [info script]] ..]]
cd $ROOT

# ⚠️ 기본 태그 `xl_g12` 를 **보드에 그대로 싣지 말 것.**
#    그것은 트랙 1(`xlse`) 모델이고 CLAUDE.md 0 이 2026-08-26 에 트랙 2
#    (`normalize: fixed`)로 가기로 했다. `xlse` 의 임계값은 채널 고유값이 아니라
#    **16채널 공통 노드 기준의 분압**이라 다이오드-OR 회로가 실제로 있어야 성립하는데,
#    동료 회로에는 없다.
#
#    그대로 실으면 합성도 되고 비트스트림도 나오고 보드도 돈다 -- **결과만 틀린다.**
#    `xl_g12` 는 데이터패스가 수치적으로 맞는지 증명하려고 뽑은 것이고 그 일은 끝났다.
#    골든 벡터는 "하드웨어가 PyTorch 와 같은 수를 내는가" 를 보지 가중치의 좋고
#    나쁨을 보지 않으므로, 그 목적에는 일관된 집합이면 무엇이든 된다.
#
#    보드용은 `bd_*` 계열(트랙 2)이다. 아날로그가 확정된 뒤 재학습 -> 학습 박스에서
#    export -> rtl/gen/<태그>/ 커밋 -> 여기에 `-tag <태그>`. **RTL 은 안 고친다.**

# ---- 인자 ---------------------------------------------------------------- #
set part  xc7s75fgga484-1
set tag   xl_g12
set top   kws_top_synth
set do_impl 0
for {set i 0} {$i < [llength $argv]} {incr i} {
    switch -- [lindex $argv $i] {
        -part { set part [lindex $argv [incr i]] }
        -tag  { set tag  [lindex $argv [incr i]] }
        -top  { set top  [lindex $argv [incr i]] }
        -impl { set do_impl 1 }
        default { puts "unknown arg: [lindex $argv $i]"; exit 1 }
    }
}

set gen  rtl/gen/$tag
set out  out/synth/$part
file mkdir $out
puts "== part $part / tag $tag / top $top =="

# ---- $readmemh 경로 ------------------------------------------------------- #
# 이것이 Vivado 로 옮길 때 실제로 깨지는 유일한 부분이다.
#
# paths.vh 는 ROM 경로를 리포 루트 기준 상대경로로 담는다("rtl/gen/<tag>/x.hex").
# Icarus 는 run_tb.sh 가 리포 루트로 cd 하므로 그대로 찾는다. Vivado 는 다르다 --
# $readmemh 를 **합성 run 디렉터리** 기준으로 찾으므로 전부 못 찾는다. 그런데
# 못 찾아도 **에러가 아니다**: ROM 이 X 로 남고 합성은 성공하며, 가중치가 전부
# 없는 회로가 조용히 나온다. 보드에 올려서야 알게 되는 종류다.
#
# 고치는 방법: .hex 를 run 디렉터리로 복사하고, paths.vh 를 파일명만 남긴 사본으로
# 바꿔 그걸 include 한다. RTL 도 emit.py 도 손대지 않는다 -- 시뮬 경로는 그대로
# 원본 paths.vh 를 쓴다.
if {![file exists $gen/paths.vh]} {
    puts "ERROR: $gen/paths.vh not found -- run the export first."
    puts "       python -m export.emit --tag $tag --out $gen"
    exit 1
}
set synth_inc $out/inc
file mkdir $synth_inc
foreach h [glob -nocomplain $gen/*.hex] { file copy -force $h $synth_inc }

set fh [open $gen/paths.vh r]; set txt [read $fh]; close $fh
# "rtl/gen/xl_g12/conv1_w.hex" -> "conv1_w.hex"
set flat [regsub -all {"[^"]*/([^"/]+\.hex)"} $txt {"\1"}]
set fh [open $synth_inc/paths.vh w]
puts $fh "// GENERATED by rtl/build.tcl -- 파일명만 남긴 사본.\
\n// 원본은 $gen/paths.vh 이고 시뮬은 그쪽을 쓴다."
puts $fh $flat
close $fh

# 래퍼가 `include "rtl/gen/active.vh" 로 태그를 고른다. 시뮬에서는 run_tb.sh 가
# 만들지만 합성 경로에는 그 스크립트가 없으므로 여기서 같은 파일을 쓴다.
set fh [open rtl/gen/active.vh w]
puts $fh "// GENERATED by rtl/build.tcl -- 합성이 읽을 export 를 고른다."
puts $fh "`include \"paths.vh\""
puts $fh "`include \"$gen/parameters.vh\""
close $fh

set n_hex [llength [glob -nocomplain $synth_inc/*.hex]]
puts "   copied $n_hex .hex files to $synth_inc, rewrote paths.vh to bare filenames"
if {$n_hex == 0} { puts "ERROR: no .hex files found"; exit 1 }

# ---- 소스 ---------------------------------------------------------------- #
# 최상위는 kws_top 이 아니라 kws_top_synth 다. kws_top 의 ROM 경로 파라미터는
# 기본값이 "" 이고 RTL 이 그걸 걸러내므로, 그냥 합성하면 **가중치가 하나도 없는
# 회로가 에러 없이** 나온다. 래퍼가 테스트벤치와 같은 매크로를 꽂아준다.
create_project -in_memory -part $part
read_verilog [concat [glob rtl/*.v] [glob rtl/synth/*.v]]
# include 검색 경로: 재작성한 paths.vh 가 원본보다 먼저 걸리도록 앞에 둔다
set_property include_dirs [list $synth_inc $gen rtl/gen] [current_fileset]
# -unmanaged: 이 파일을 **온전한 Tcl 스크립트**로 취급하라는 뜻이다.
#
# 그냥 read_xdc 로 넣으면 Vivado 가 XDC 를 **제한된 부분집합**으로 읽고
# for / if / proc 를 거부한다 (2026-09-08 에 bringup.xdc 로 실측):
#
#     CRITICAL WARNING: [Designutils 20-1307] Command 'foreach' is not
#                       supported in the xdc constraint file.
#
# 거부한 자리를 **통째로 건너뛰고 계속 간다.** kws_top.xdc 는 핀 배정을 proc 과
# for 안에서 하므로, 그러면 제약이 하나도 안 걸린 채 합성이 "성공" 한다.
#
# bringup 쪽은 source 로 옮겨서 풀었는데(synth_design 뒤로), 여기는 그 방법이
# 덜 좋다. kws_top.xdc 의 [1] 타이밍 절(create_clock / set_false_path /
# ASYNC_REG)은 XDC 문법으로 전부 합법이고 **합성 중에 있어야 제 값을 한다**.
# 뒤로 옮기면 합성이 클럭 없이 돌아간다. -unmanaged 는 위치를 안 옮기고
# 제한만 푼다.
read_xdc -unmanaged rtl/constraints/kws_top.xdc

# ---- 합성 ---------------------------------------------------------------- #
# -flatten_hierarchy none: 계층을 유지해야 utilization 이 모듈별로 나온다.
# 어느 블록이 무엇을 먹는지가 이 단계에서 알고 싶은 전부다.
synth_design -top $top -flatten_hierarchy none

# ---- 타이밍 제약이 실제로 걸렸는지 확인한다 -------------------------------- #
# 이 검사를 두는 이유는 제약이 날아가는 방식이 **조용하기** 때문이다. 브링업에서는
# write_bitstream 앞의 DRC 가 막아 줬지만, 여기는 기본으로 -impl 을 안 하므로
# 비트스트림도 DRC 도 없다. 제약이 통째로 날아가도 utilization 과 timing 리포트가
# 멀쩡하게 나오고, 그 리포트는 **우리가 묻는 질문에 답하지 않는 리포트**다.
#
# **핀 배치는 여기서 검사하지 않는다.** 2026-09-08 에 한 번 그렇게 썼다가 틀렸다:
#
#     INFO: Property 'PACKAGE_PIN' is not supported for elaborated designs
#     INFO: [Project 1-236] Implementation specific constraints were found ...
#           will be ignored for synthesis but will be used in implementation
#
# 핀 배치는 배치배선의 입력이지 합성의 입력이 아니다. 합성 단계에서 0 인 것이
# 정상이므로, 그걸 실패로 삼으면 멀쩡한 합성을 막는다. 핀은 -impl 쪽에서
# write_bitstream 앞의 DRC (UCIO-1 / NSTD-1) 가 잡는다 -- 그게 제 자리다.
#
# 합성 단계에서 의미 있는 검사는 **클럭**이다. 없으면 timing_synth.rpt 가
# 「제약 없음」이 되고, 그건 통과가 아니라 아무것도 안 잰 것이다.
if {[llength [get_clocks -quiet]] == 0} {
    puts "ERROR: no clocks were defined -- kws_top.xdc section \[1\] did not run."
    puts "       timing_synth.rpt would be meaningless, so stopping here."
    puts "       Look above for errors from the constraint file."
    exit 1
}
puts "== clocks: [get_clocks] =="

report_utilization      -hierarchical -file $out/utilization.rpt
report_timing_summary   -file $out/timing_synth.rpt
write_checkpoint -force $out/post_synth.dcp

# ROM 이 실제로 채워졌는지. $readmemh 가 조용히 실패하면 여기서 BRAM/LUTRAM 이
# 0 으로 나오므로, 리포트를 사람이 안 열어봐도 로그에 남는다.
set bram [get_cells -quiet -hier -filter {PRIMITIVE_GROUP == BMEM}]
puts "== BRAM cells: [llength $bram] =="
if {[llength $bram] == 0} {
    puts "WARNING: no BRAM was inferred. Check the \$readmemh paths or ROM sizes."
    puts "         A silent \$readmemh failure looks exactly like this."
}

if {$do_impl} {
    # 배치배선은 핀 제약이 있어야 의미가 있다. xdc 2 절이 아직 미결이므로
    # 기본으로는 안 돈다.
    opt_design
    place_design
    route_design
    report_timing_summary -file $out/timing_impl.rpt
    report_utilization    -file $out/utilization_impl.rpt
    write_checkpoint -force $out/post_route.dcp

    # 핀이 하나라도 제약 없이 남아 있으면 여기서 DRC 가 막는다. 그게 맞다 --
    # 미제약 핀은 도구가 임의로 배정하므로, 보드에 올리면 신호가 우리가 배선한
    # 곳이 아닌 데로 나가고 증상은 "동작 안 함" 뿐이다.
    write_bitstream -force $out/kws_top.bit
    puts "== bitstream: $out/kws_top.bit =="
}

puts "== done. artifacts in $out =="
