# 배치 합성 — GUI 없이 한 줄로. 결과가 재현 가능해진다.
#
#   vivado -mode batch -source rtl/build.tcl
#   vivado -mode batch -source rtl/build.tcl -tclargs -part xc7k160tffg676-2
#   vivado -mode batch -source rtl/build.tcl -tclargs -tag fx_ste0003 -impl
#
# 리포 루트에서 돌린다. 산출물은 out/synth/<part>/ 에 쌓인다.
#
# ⚠️ 파트 기본값 xc7k325t 는 KC705 지만 **무료 Vivado ML Standard 대상이 아니다**
#    (Enterprise 필요). 무료 툴로 RTL 을 먼저 털어내려면 -part 로 작은 파트를 준다:
#    합성이 잡는 문제(추론 안 되는 래치, 폭 truncation, $readmemh 실패, 타이밍)는
#    대부분 파트와 무관하므로, 작은 파트에서 깨끗하면 연구실에서 파트만 바꿔
#    다시 돌리면 된다. 프로젝트 파일은 에디션과 무관하다.

set ROOT [file normalize [file join [file dirname [info script]] ..]]
cd $ROOT

# ---- 인자 ---------------------------------------------------------------- #
set part  xc7k325tffg900-2
set tag   xl_g12
set top   kws_top_synth
set do_impl 0
for {set i 0} {$i < [llength $argv]} {incr i} {
    switch -- [lindex $argv $i] {
        -part { set part [lindex $argv [incr i]] }
        -tag  { set tag  [lindex $argv [incr i]] }
        -top  { set top  [lindex $argv [incr i]] }
        -impl { set do_impl 1 }
        default { puts "unknown arg: [lindex $argv $i]"; exit 1 }
    }
}

set gen  rtl/gen/$tag
set out  out/synth/$part
file mkdir $out
puts "== part $part / tag $tag / top $top =="

# ---- $readmemh 경로 ------------------------------------------------------- #
# 이것이 Vivado 로 옮길 때 실제로 깨지는 유일한 부분이다.
#
# paths.vh 는 ROM 경로를 리포 루트 기준 상대경로로 담는다("rtl/gen/<tag>/x.hex").
# Icarus 는 run_tb.sh 가 리포 루트로 cd 하므로 그대로 찾는다. Vivado 는 다르다 --
# $readmemh 를 **합성 run 디렉터리** 기준으로 찾으므로 전부 못 찾는다. 그런데
# 못 찾아도 **에러가 아니다**: ROM 이 X 로 남고 합성은 성공하며, 가중치가 전부
# 없는 회로가 조용히 나온다. 보드에 올려서야 알게 되는 종류다.
#
# 고치는 방법: .hex 를 run 디렉터리로 복사하고, paths.vh 를 파일명만 남긴 사본으로
# 바꿔 그걸 include 한다. RTL 도 emit.py 도 손대지 않는다 -- 시뮬 경로는 그대로
# 원본 paths.vh 를 쓴다.
if {![file exists $gen/paths.vh]} {
    puts "ERROR: $gen/paths.vh 가 없다. export 를 먼저 돌린다."
    exit 1
}
set synth_inc $out/inc
file mkdir $synth_inc
foreach h [glob -nocomplain $gen/*.hex] { file copy -force $h $synth_inc }

set fh [open $gen/paths.vh r]; set txt [read $fh]; close $fh
# "rtl/gen/xl_g12/conv1_w.hex" -> "conv1_w.hex"
set flat [regsub -all {"[^"]*/([^"/]+\.hex)"} $txt {"\1"}]
set fh [open $synth_inc/paths.vh w]
puts $fh "// GENERATED by rtl/build.tcl -- 파일명만 남긴 사본.\
\n// 원본은 $gen/paths.vh 이고 시뮬은 그쪽을 쓴다."
puts $fh $flat
close $fh

# 래퍼가 `include "rtl/gen/active.vh" 로 태그를 고른다. 시뮬에서는 run_tb.sh 가
# 만들지만 합성 경로에는 그 스크립트가 없으므로 여기서 같은 파일을 쓴다.
set fh [open rtl/gen/active.vh w]
puts $fh "// GENERATED by rtl/build.tcl -- 합성이 읽을 export 를 고른다."
puts $fh "`include \"paths.vh\""
puts $fh "`include \"$gen/parameters.vh\""
close $fh

set n_hex [llength [glob -nocomplain $synth_inc/*.hex]]
puts "   .hex $n_hex 개를 $synth_inc 로 복사, paths.vh 를 파일명 기준으로 재작성"
if {$n_hex == 0} { puts "ERROR: .hex 가 하나도 없다"; exit 1 }

# ---- 소스 ---------------------------------------------------------------- #
# 최상위는 kws_top 이 아니라 kws_top_synth 다. kws_top 의 ROM 경로 파라미터는
# 기본값이 "" 이고 RTL 이 그걸 걸러내므로, 그냥 합성하면 **가중치가 하나도 없는
# 회로가 에러 없이** 나온다. 래퍼가 테스트벤치와 같은 매크로를 꽂아준다.
create_project -in_memory -part $part
read_verilog [concat [glob rtl/*.v] [glob rtl/synth/*.v]]
# include 검색 경로: 재작성한 paths.vh 가 원본보다 먼저 걸리도록 앞에 둔다
set_property include_dirs [list $synth_inc $gen rtl/gen] [current_fileset]
read_xdc rtl/constraints/kws_top.xdc

# ---- 합성 ---------------------------------------------------------------- #
# -flatten_hierarchy none: 계층을 유지해야 utilization 이 모듈별로 나온다.
# 어느 블록이 무엇을 먹는지가 이 단계에서 알고 싶은 전부다.
synth_design -top $top -flatten_hierarchy none

report_utilization      -hierarchical -file $out/utilization.rpt
report_timing_summary   -file $out/timing_synth.rpt
write_checkpoint -force $out/post_synth.dcp

# ROM 이 실제로 채워졌는지. $readmemh 가 조용히 실패하면 여기서 BRAM/LUTRAM 이
# 0 으로 나오므로, 리포트를 사람이 안 열어봐도 로그에 남는다.
set bram [get_cells -quiet -hier -filter {PRIMITIVE_GROUP == BMEM}]
puts "== BRAM 셀 [llength $bram] 개 =="
if {[llength $bram] == 0} {
    puts "WARNING: BRAM 이 하나도 추론되지 않았다. \$readmemh 경로나 ROM 크기를 확인할 것."
}

if {$do_impl} {
    # 배치배선은 핀 제약이 있어야 의미가 있다. xdc 2 절이 아직 미결이므로
    # 기본으로는 안 돈다.
    opt_design
    place_design
    route_design
    report_timing_summary -file $out/timing_impl.rpt
    report_utilization    -file $out/utilization_impl.rpt
    write_checkpoint -force $out/post_route.dcp
}

puts "== 완료. 산출물: $out =="
