#!/usr/bin/env bash
# Lint, then build and run one testbench. Run from anywhere in the repo.
#
#   ./rtl/run_tb.sh bin_mac
#   ./rtl/run_tb.sh top xl_g12                    # the export's own vectors
#   ./rtl/run_tb.sh top xl_g12 out/cmp_vectors    # an analog trace instead
#
#   sudo apt install -y iverilog verilator     # Debian/Ubuntu/WSL
#   brew install icarus-verilog verilator      # macOS
#
# Lint and simulation catch different things, so both run. Lint reads the code
# and finds width truncation or an unintended latch without any stimulus;
# simulation runs it and finds values that disagree with the golden vectors,
# but only for data that reaches the bug. Verilator is used lint-only -- as a
# simulator it is 2-state and would not propagate X, so an unreset register
# reads as 0 and the bug survives to the board.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

NAME="${1:-bin_mac}"
# Which export to run against. The RTL does not contain the tag anywhere -- an
# analog change costs a retrain and a new .hex, never an edit to a .v
# (docs/ICD.md) -- so switching tracks is switching which generated headers the
# testbenches include, and nothing else.
TAG="${2:-xl_g12}"
GEN="rtl/gen/${TAG}"
# Optional third argument: a vector directory to run against INSTEAD of the
# export's own golden vectors -- how a comparator trace from the analog side
# gets classified (experiments/trace_to_frames.py --vectors). The weights still
# come from the tag; only the stimulus and the expected class change.
GOLD="${3:-${GEN}/golden}"
[ -d "$GEN" ] || { echo "no such export: $GEN" >&2; exit 1; }
for f in parameters.vh paths.vh; do
    [ -f "$GEN/$f" ] || { echo "missing $GEN/$f -- re-run export.emit and "\
                               "export.golden for tag $TAG" >&2; exit 1; }
done
[ -f "$GOLD/paths.vh" ] || { echo "missing $GOLD/paths.vh" >&2; exit 1; }
# one generated file selects the tag; the testbenches include only this
mkdir -p rtl/gen
cat > rtl/gen/active.vh <<EOF
// GENERATED by rtl/run_tb.sh -- selects which export the testbenches read.
\`include "${GEN}/parameters.vh"
\`include "${GEN}/paths.vh"
\`include "${GOLD}/paths.vh"
EOF
DUT="rtl/kws_${NAME}.v"
TB="rtl/tb/tb_${NAME}.v"
# every module, not just the DUT: modules instantiate each other
# (dw_conv wraps bin_mac) and a missing one is a link error, not a
# design question worth asking the caller about
ALL_RTL=$(ls rtl/*.v)
# kws_board_top 은 kws_top_synth 를 인스턴스화하는데 그 파일은 rtl/synth/ 에 있어
# 위 글롭에 안 걸린다. board_top 을 돌릴 때만 붙인다 -- 다른 테스트에까지 넣으면
# 매크로로 파라미터를 전부 박은 네트워크가 한 벌 더 엘라보레이션된다.
[ "$NAME" = board_top ] && ALL_RTL="$ALL_RTL $(ls rtl/synth/*.v)"
[ -f "$DUT" ] || { echo "no such module: $DUT" >&2; exit 1; }
[ -f "$TB" ]  || { echo "no testbench: $TB" >&2; exit 1; }

if command -v verilator >/dev/null 2>&1; then
    echo "== lint =="
    # -DKWS_ASSERT here too, and not only for the simulator: without it the
    # assertion block is invisible to lint, so the upper bits of the wide
    # accumulator look unused and lint is checking a different configuration
    # than the one that runs. Lint should see the code the simulator sees.
    # -Wall minus the style-only ones that fight Verilog-2001 conventions.
    echo "tag: ${TAG}"
    verilator --lint-only -Wall -DKWS_ASSERT -I. \
              -Wno-DECLFILENAME -Wno-VARHIDDEN \
              --top-module "kws_${NAME}" $ALL_RTL
    echo "lint clean"
else
    echo "== lint skipped (verilator not installed) =="
fi

echo "== simulate =="
OUT="$(mktemp -d)/tb_${NAME}"
LOG="${OUT}.log"
# -DKWS_ASSERT arms the accumulator bound checks inside the DUT.
# -I. so the testbench can include the generated vectors/expect.vh by repo path.
#
# -s 로 루트를 못박는다. 없으면 iverilog 가 **아무도 인스턴스화하지 않는 모듈을
# 전부 루트로 잡아** 엘라보레이션한다. kws_board_top 이 생기면서(2026-09-10) 그게
# 문제가 됐다 -- 그 모듈이 rtl/synth/kws_top_synth 를 부르는데 위 글롭에 없어서
# **모든 단위 테스트가** "Unknown module type: kws_top_synth" 로 죽었다.
#
# verilator 는 --top-module 이 있어서 거기까지 가지 않았고, 그래서 lint 는
# 통과하고 시뮬만 죽는 모양이 됐다. 루트를 양쪽 다 못박아 그 비대칭을 없앤다.
iverilog -g2005 -Wall -DKWS_ASSERT -I. -s "tb_${NAME}" -o "$OUT" $ALL_RTL "$TB"
vvp "$OUT" | tee "$LOG"

# Do not rely on $fatal to set the exit status: it is a SystemVerilog task and
# what a Verilog-2005 simulator does with it varies. The log is the contract.
if grep -qE '^(FAIL|ASSERT)' "$LOG"; then
    echo "FAILED -- see above" >&2
    exit 1
fi
# ", 0 failures" and not "0 failures": the latter also matches "10 failures".
grep -qE ', 0 failures' "$LOG" || { echo "no pass line in output" >&2; exit 1; }

# Record it. Until now a run's result lived only in terminal scrollback, so
# "what has been verified against what" was something a person remembered
# rather than something the repo knew -- and that is exactly the kind of claim
# that rots. docs/make_site.py reads this file; nothing else may write it.
RES="rtl/results.json"
CHECKED=$(grep -oE '[0-9]+ frames checked' "$LOG" | tail -1 | grep -oE '^[0-9]+')
python3 - "$RES" "$NAME" "${CHECKED:-0}" "$LOG" "$TAG" <<'EOPY'
import json, pathlib, subprocess, sys, datetime
path, name, checked, log, tag = sys.argv[1:6]
checked = int(checked)
p = pathlib.Path(path)
data = json.loads(p.read_text()) if p.is_file() else {}
sha = subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                     capture_output=True, text=True).stdout.strip()
# 키는 모듈 이름 하나다. 즉 **같은 모듈을 다른 태그로 돌리면 앞 기록을 덮는다** --
# 이 파일은 "지금 검증된 상태" 를 담지 이력을 담지 않는다. 그래서 태그를 안 적으면
# "무엇을 무엇에 대해 검증했는가" 의 뒷부분이 통째로 빈다. 이 파일이 존재하는 이유가
# 바로 그 문장인데(아래 원주석) 정작 대상이 빠져 있었다.
data[name] = {
    "passed": True,
    "tag": tag,
    "checked": checked,
    "commit": sha,
    "when": datetime.datetime.now().astimezone().isoformat(timespec="seconds"),
    "lines": [l for l in pathlib.Path(log).read_text().splitlines()
              if l.startswith("ok ") or "failures" in l],
}
p.write_text(json.dumps(dict(sorted(data.items())), indent=2) + "\n")
print(f"recorded {name}: {checked} checked -> {path}")
EOPY
