[CmdletBinding()]
param(
    [string]$Name = "board_top",
    [string]$Tag = "xl_g12",
    [string]$Vectors = "",
    [switch]$Gui
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

function Invoke-Checked {
    param(
        [Parameter(Mandatory = $true)][string]$Command,
        [Parameter(Mandatory = $true)][string[]]$Arguments
    )

    Write-Host "== $Command $($Arguments -join ' ') =="
    & $Command @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "$Command failed with exit code $LASTEXITCODE"
    }
}

$repo = (& git rev-parse --show-toplevel).Trim()
if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($repo)) {
    throw "run_xsim.ps1 must be run inside the repository"
}

$oldLocation = Get-Location
Set-Location $repo
try {
    $genRel = "rtl/gen/$Tag"
    $gen = Join-Path $repo $genRel
    if ([string]::IsNullOrWhiteSpace($Vectors)) {
        $vectorsRel = "$genRel/golden"
        $vectors = Join-Path $repo $vectorsRel
    } else {
        $vectors = (Resolve-Path -LiteralPath $Vectors).Path
        $vectorsRel = (Resolve-Path -LiteralPath $vectors -Relative).Replace('\', '/')
        if ($vectorsRel.StartsWith('./')) {
            $vectorsRel = $vectorsRel.Substring(2)
        }
    }

    foreach ($path in @(
        (Join-Path $gen "parameters.vh"),
        (Join-Path $gen "paths.vh"),
        (Join-Path $vectors "paths.vh")
    )) {
        if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
            throw "missing required file: $path"
        }
    }

    $activePath = Join-Path $repo "rtl/gen/active.vh"
    $activeLines = @(
        "// GENERATED by rtl/run_xsim.ps1 -- selects the export and vectors.",
        ('`include "' + $genRel + '/parameters.vh"'),
        ('`include "' + $genRel + '/paths.vh"'),
        ('`include "' + $vectorsRel + '/paths.vh"')
    )
    [IO.File]::WriteAllLines(
        $activePath,
        $activeLines,
        [Text.UTF8Encoding]::new($false)
    )

    $tbName = "tb_$Name"
    $tb = Join-Path $repo "rtl/tb/$tbName.v"
    if (-not (Test-Path -LiteralPath $tb -PathType Leaf)) {
        throw "no testbench: $tb"
    }

    $rtlFiles = @(
        Get-ChildItem -LiteralPath (Join-Path $repo "rtl") -Filter "*.v"
        Get-ChildItem -LiteralPath (Join-Path $repo "rtl/synth") -Filter "*.v"
    ) | Sort-Object FullName | ForEach-Object FullName

    $out = Join-Path $repo "out/xsim/$Name"
    New-Item -ItemType Directory -Force -Path $out | Out-Null
    $snapshot = "${tbName}_sim"

    $xvlogArgs = @(
        "--work", "xil_defaultlib",
        "--include", $repo,
        "--define", "KWS_ASSERT",
        "--log", (Join-Path $out "xvlog.log")
    ) + $rtlFiles + @($tb)
    Invoke-Checked -Command "xvlog" -Arguments $xvlogArgs

    $xelabArgs = @(
        "--debug", "typical",
        "--mt", "auto",
        "--snapshot", $snapshot,
        "--log", (Join-Path $out "xelab.log"),
        "xil_defaultlib.$tbName"
    )
    Invoke-Checked -Command "xelab" -Arguments $xelabArgs

    $xsimArgs = @(
        $snapshot,
        "--wdb", (Join-Path $out "$snapshot.wdb"),
        "--log", (Join-Path $out "xsim.log")
    )
    if ($Gui) {
        $xsimArgs += @("--gui", "--onerror", "stop", "--onfinish", "stop")
        Write-Host "In the XSim GUI, add the signals you want and click Run All."
        Invoke-Checked -Command "xsim" -Arguments $xsimArgs
    } else {
        $xsimArgs += @("--runall", "--onerror", "quit", "--onfinish", "quit")
        Invoke-Checked -Command "xsim" -Arguments $xsimArgs

        $simLog = Get-Content -LiteralPath (Join-Path $out "xsim.log") -Raw
        if ($simLog -match '(?m)^(FAIL|ASSERT)') {
            throw "simulation reported FAIL or ASSERT; see $out/xsim.log"
        }
        if ($simLog -notmatch ', 0 failures') {
            throw "simulation did not print its pass line; see $out/xsim.log"
        }
        Write-Host "== PASS: $Name ($Tag) =="
        Write-Host "   log: $out/xsim.log"
        Write-Host "   wave: $out/$snapshot.wdb"
    }
} finally {
    Set-Location $oldLocation
}
