"""Test vectors for tb_bin_mac, packed by the SAME code that packs the ROMs.

The point is not to produce test data -- random +-1 vectors are trivial. It is
that the testbench must not carry its own idea of the bit order. If the vectors
were hand-packed here and export/pack.py later changed (or was already
misunderstood), the testbench would agree with itself and disagree with the
hardware's actual weights. So the packing comes from pack_pm1, and the expected
accumulator comes from a plain dot product.

Cases are chosen for the two things that actually break:

  * a length that is NOT a multiple of 32, so the zero-padded tail decodes as
    -1 and must be masked. This is the classic silent bug: it produces a small
    plausible error, not a crash.
  * an asymmetric bit pattern, so a reversed word order fails instead of
    passing by symmetry (same reason tests/test_export.py uses one).

THE OUTPUT IS COMMITTED. It needs torch, which lives on the training box, but
the testbench needs it anywhere iverilog runs -- including machines that will
never have a checkpoint. The files are small and the generator is seeded, so
they travel with the repo as fixtures rather than being rebuilt per machine.

Run (from the repo root):  python rtl/tb/make_mac_vectors.py
"""
from __future__ import annotations

import sys
from pathlib import Path

# run as `python rtl/tb/make_mac_vectors.py` from the repo root: that puts
# rtl/tb on sys.path, not the root, so export/ is not importable without this
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import torch

from export.pack import pack_pm1, to_hex_words, WORD_BITS

OUT = Path(__file__).resolve().parent / "vectors"

# (name, n_terms) -- 13 and 29 are real depthwise kernels, 64/128 real
# pointwise widths, 33 and 31 straddle the word boundary on purpose
CASES = [("k13", 13), ("k29", 29), ("w31", 31), ("w32", 32), ("w33", 33),
         ("c64", 64), ("c128", 128)]


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    g = torch.Generator().manual_seed(0)
    lines = []

    for name, n in CASES:
        a = torch.where(torch.rand(n, generator=g) > 0.5, 1.0, -1.0)
        w = torch.where(torch.rand(n, generator=g) > 0.5, 1.0, -1.0)
        # an asymmetric case too: first half +1, rest -1, so a reversed word
        # order changes the answer
        if name == "w33":
            a = torch.cat([torch.ones(17), -torch.ones(n - 17)])

        expect = int(torch.dot(a, w).item())
        pa, pw = pack_pm1(a.unsqueeze(0)), pack_pm1(w.unsqueeze(0))
        (OUT / f"{name}_act.hex").write_text("\n".join(to_hex_words(pa)) + "\n")
        (OUT / f"{name}_wgt.hex").write_text("\n".join(to_hex_words(pw)) + "\n")
        lines.append(f"{name} {n} {pa.n_words} {expect}")
        print(f"{name:>5}  n={n:>4}  words={pa.n_words}  expect={expect:>5}")

    (OUT / "cases.txt").write_text("\n".join(lines) + "\n")

    # The expected values go into Verilog as defines rather than being read at
    # runtime: $fscanf portability across simulators is not worth the risk, and
    # a hand-copied number in the testbench is exactly the drift this script
    # exists to prevent.
    vh = ["// GENERATED by rtl/tb/make_mac_vectors.py -- do not edit.",
          "`ifndef KWS_MAC_EXPECT_VH", "`define KWS_MAC_EXPECT_VH"]
    for line in lines:
        nm, n, nw, ex = line.split()
        vh.append(f"`define {nm.upper()}_EXPECT {ex}")
        vh.append(f"`define {nm.upper()}_NWORDS {nw}")
    vh.append("`endif")
    (OUT / "expect.vh").write_text("\n".join(vh) + "\n")
    print(f"\nwrote {len(CASES)} cases to {OUT}")
    print(f"word_bits={WORD_BITS}; cases.txt is 'name n_valid n_words expected'")


if __name__ == "__main__":
    main()
